version: '3.9'

services:
  wordpress:
    container_name: wordpress-ra-yoga
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "${WP_PORT}:80"   
    restart: always
    environment:
      WORDPRESS_DB_HOST: 'db:${MYSQL_PORT}'
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASS}
      WORDPRESS_DB_NAME: ${WP_DB}     

  db:
    container_name: db-mysql-ra-yoga
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MYSQL_DATABASE: ${WP_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${WP_DB_PASS}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    container_name: php-myadmin-ra-yoga
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASS}

volumes:
    wordpress_files:
    db_data:
